### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by poyhsiao** [EXSyst/recent-projects#18]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0-6169caa
**System**: Mac OS X 10.10.2
**Thrown From**: [recent-projects](https://github.com/Exter-N/recent-projects) package, v0.3.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html?loadSettings=%7B%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.176.0-6169caa%22%2C%22shellLoadTime%22%3A320%7D:0

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at /Users/kimhsiao/.atom/packages/recent-projects/lib/recent-projects.coffee:17:25
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-compile-coffee",
      "ask-stack",
      "minimap"
    ],
    "themes": [
      "seti-ui",
      "monokai-seti"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
auto-update-packages, v0.2.2
autoclose-html, v0.14.0
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
autocomplete-snippets, v0.3.2
color-picker, v1.4.4
css-color-highlight, v0.3.0
docblockr, v0.5.8
editor-stats, v0.16.0
editorconfig, v0.3.0
file-icons, v1.4.8
hex, v0.5.0
language-iced-coffeescript, v0.1.0
language-jade, v0.3.0
linter, v0.10.1
linter-coffeelint, v0.1.7
linter-csslint, v0.0.11
linter-htmlhint, v0.0.8
linter-js-yaml, v0.1.3
linter-jshint, v0.1.0
linter-php, v0.0.11
linter-shellcheck, v0.0.6
localization, v1.16.1
markdown-format, v2.5.0
minimap-git-diff, v3.1.1
minimap-highlight-selected, v3.1.2
monokai-seti, v0.4.0
open-last-project, v0.1.1
open-recent, v2.2.0
recent-projects, v0.3.0
seti-ui, v0.6.1
terminal-status, v1.3.5
web-browser, v0.2.3
web-view, v0.3.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by malko** [comment]
This make the package unusable at all at the moment

**Comment by Ener-Getick** [comment]
Does this bug still exist ?

**Comment by Ener-Getick** [comment]
Can you provide me your recent-project json file please ?
It is located in atom folder : recent-project.json

**Comment by malko** [comment]
The content of the file is ```[]```

I just reinstalled the package, open a new atom and see my actual procject in the list.
Then i closed both window and restart another atom instance without path parameter, i got my last active project opened. Finally opening recent-projects show me an empty list of no projects at all.

**Comment by Ener-Getick** [comment]
See https://github.com/EXSyst/recent-projects/issues/29#issuecomment-118431178

**Comment by Ener-Getick** [comment]
Does the last version fix this error ?
