### ISSUE TITLE
Failed to activate the recent-projects package

### ISSUE THREAD

**Issue by tarasis** [EXSyst/recent-projects#25]
[Enter steps to reproduce below:]

1. Started Atom 0.194 - As soon as main UI appears an error dialog saying it failed to active recent-projects package.

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [recent-projects](https://github.com/Exter-N/recent-projects) package, v0.3.0

### Stack Trace

Failed to activate the recent-projects package

```
At Cannot read property 'trigger' of undefined

TypeError: Cannot read property 'trigger' of undefined
    at Object.module.exports.activate (/Users/rob/.atom/packages/recent-projects/lib/main.coffee:104:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "open-last-project",
      "autocomplete-plus",
      "autocomplete-paths"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "projectHome": "/User/rob/Programming/Projects/Current"
  }
}
```

### Installed Packages

```coffee
# User
language-swift, v0.4.0
minimap, v4.7.6
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.1
minimap-selection, v4.2.0
recent-projects, v0.3.0
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by Ener-Getick** [comment]
Fixed by https://github.com/EXSyst/recent-projects/commit/b68d92dbf54ba8867f3d20292558b1596324981d.
Thank you.
