### ISSUE TITLE
Failed to activate the recent-projects package

### ISSUE THREAD

**Issue by nanorepublica** [EXSyst/recent-projects#26]
[Enter steps to reproduce below:]

1.  Start Atom - happens everytime

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [recent-projects](https://github.com/Exter-N/recent-projects) package, v0.3.0

### Stack Trace

Failed to activate the recent-projects package

```
At Cannot read property 'trigger' of undefined

TypeError: Cannot read property 'trigger' of undefined
    at Object.module.exports.activate (/Users/amiller/.atom/packages/recent-projects/lib/main.coffee:104:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "travis-ci-status"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/Users/amiller"
  },
  "recent-projects": {
    "textOnly": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
angularjs-helper, v0.8.0
angularjs-snippets, v0.10.2
atom-angularjs, v0.1.2
atom-cli-diff, v0.11.0
atom-django, v0.2.1
atom-jinja2, v0.5.0
atom-runner, v2.3.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
build, v0.29.0
color-picker, v1.7.0
command-logger, v0.23.0
django-templates, v0.4.0
editor-stats, v0.17.0
eval, v0.2.0
git-blame, v0.4.0
git-go, v1.0.1
git-grep, v0.9.0
git-history, v2.5.0
git-log, v0.3.0
git-tab-status, v1.7.0
inline-autocomplete, v1.0.4
jsonlint, v1.1.0
language-django, v0.1.1
language-docker, v1.1.3
language-puppet, v0.11.0
language-python-django-templates, v0.1.0
linter, v0.12.0
linter-puppet, v0.1.0
linter-puppet-lint, v0.2.8
minimap, v4.7.6
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.1
minimap-selection, v4.2.0
monokai, v0.14.0
pretty-json, v0.3.3
project-colorize, v0.1.0
project-manager, v1.15.5
project-ring, v0.19.6
recent-files, v0.3.0
recent-projects, v0.3.0
script, v2.19.0
set-syntax, v0.2.1
update-packages, v0.1.0

# Dev
No dev packages
```

**Comment by vnt** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [recent-projects](https://github.com/EXSyst/recent-projects) package 0.13.1


### Stack Trace

Failed to activate the recent-projects package

```
At 'super' keyword unexpected here

SyntaxError: 'super' keyword unexpected here
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/recent-projects/lib/main.js:8:26)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:826:28
```

### Commands

```
     -0:27.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
cakephp3-snippets 0.5.0 
chrome-color-picker 0.8.0 
color-picker 2.2.5 
color-tabs 0.1.8 
css-color-name 0.4.0 
file-icons 2.0.17 
file-types 0.5.5 
git-plus 7.3.3 
git-time-machine 1.5.6 
goto-definition 1.2.0 
linter 1.11.23 
linter-csslint 1.3.4 
linter-htmlhint 1.3.2 
linter-jshint 3.0.3 
linter-php 1.3.1 
minimap 4.26.8 
minimap-find-and-replace 4.5.2 
open-recent 5.0.0 
pigments 0.39.0 
pinegrow-atom 0.3.1 
recent-projects 0.13.1 
simple-drag-drop-text 0.3.4 
tag 0.4.0 
todo-show 1.11.0 
tree-view-autoresize 1.5.0 
```

**Comment by GuilhemN** [comment]
@vnt please open a new issue next time, see https://github.com/EXSyst/recent-projects/issues/50.
Thanks anyway!
