### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by donCarlosOne** [EXSyst/recent-projects#28]
[Enter steps to reproduce below:]

1. Open Atom after previously closing with a project loaded
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [recent-projects](https://github.com/EXSyst/recent-projects) package, v0.4.3

### Stack Trace

Uncaught SyntaxError: Unexpected token .

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fdoncarlos%2FDocuments%2FVelloe%2Fwww%2Fcto.velloe.com%22%7D%2C%7B%22pathToOpen%22%3A%22%2FUsers%2Fdoncarlos%2FDocuments%2FVelloe%2Fwww%2Fscto.velloe.com%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.0%22%2C%22shellLoadTime%22%3A796%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fdoncarlos%2FDocuments%2FVelloe%2Fwww%2Fcto.velloe.com%22%2C%22%2FUsers%2Fdoncarlos%2FDocuments%2FVelloe%2Fwww%2Fscto.velloe.com%22%5D%7D:1

SyntaxError: Unexpected token .
    at Object.parse (native)
    at /Users/doncarlos/.atom/packages/recent-projects/lib/recent-projects.js:24:25
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-space-pen-views",
      "tool-bar-main",
      "toolbar-basic",
      "atom-project",
      "project-ring",
      "project-switcher",
      "project-view",
      "project-quick-open",
      "autohide-tree-view"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner-php, v1.0.0
atom-ternjs, v0.6.7
autocomplete-php, v0.3.6
color-picker, v2.0.7
git-projects, v1.14.1
indent-guide-improved, v1.4.0
js-refactor, v0.4.2
jsformat, v0.9.0
jshint, v1.3.8
language-javascript-better, v1.5.0
language-php, v0.26.0
linter-js-standard, v1.0.4
linter-php, v0.0.15
local-history, v3.2.3
minimap, v4.10.1
php-debug, v0.1.2
php-getters-setters, v0.5.5
php-introspector, v1.0.0
php-twig, v4.0.0
pretty-json, v0.4.1
project-colorize, v0.2.0
project-manager, v1.15.10
recent-projects, v0.4.3
spec-tree-view, v0.1.0
symbols-tree-view, v0.9.3
synced-sidebar, v0.4.0
tool-bar, v0.1.8
toolbar-iconshortcuts, v0.3.0
tree-view-finder, v0.2.1
tree-view-open-files, v0.2.4

# Dev
No dev packages
```

**Comment by Ener-Getick** [comment]
Can you provide me the recent-project json file please ?
It is located in the atom folder : recent-project.json.

**Comment by donCarlosOne** [comment]
Here you …








…charles


+27 (0) 760119350
Cape Town

**Comment by Ener-Getick** [comment]
See https://github.com/EXSyst/recent-projects/issues/29#issuecomment-118431178

**Comment by Ener-Getick** [comment]
Does the last version fix this error ?
