### ISSUE TITLE
Uncaught SyntaxError: Unexpected token a

### ISSUE THREAD

**Issue by davidperezgar** [EXSyst/recent-projects#31]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [recent-projects](https://github.com/EXSyst/recent-projects) package, v0.4.3

### Stack Trace

Uncaught SyntaxError: Unexpected token a

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fdavidperezgar%2FWeb%2Fhispasur%22%7D%2C%7B%22pathToOpen%22%3A%22%2FUsers%2Fdavidperezgar%2FWeb%2Fgasoalhambra%22%7D%2C%7B%22pathToOpen%22%3A%22%2FUsers%2Fdavidperezgar%2FWeb%2Finmsol%22%7D%2C%7B%22pathToOpen%22%3A%22%2FUsers%2Fdavidperezgar%2FWeb%2Flandajo%22%7D%2C%7B%22pathToOpen%22%3A%22%2FUsers%2Fdavidperezgar%2FWeb%2Fbonotel%22%7D%2C%7B%22pathToOpen%22%3A%22%2FUsers%2Fdavidperezgar%2FWeb%2Fdev%22%7D%2C%7B%22pathToOpen%22%3A%22%2FUsers%2Fdavidperezgar%2FWeb%2Fphp-crm-api-functions%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.2%22%2C%22shellLoadTime%22%3A362%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fdavidperezgar%2FWeb%2Fbonotel%22%2C%22%2FUsers%2Fdavidperezgar%2FWeb%2Fdev%22%2C%22%2FUsers%2Fdavidperezgar%2FWeb%2Fgasoalhambra%22%2C%22%2FUsers%2Fdavidperezgar%2FWeb%2Fhispasur%22%2C%22%2FUsers%2Fdavidperezgar%2FWeb%2Finmsol%22%2C%22%2FUsers%2Fdavidperezgar%2FWeb%2Flandajo%22%2C%22%2FUsers%2Fdavidperezgar%2FWeb%2Fphp-crm-api-functions%22%5D%7D:1

SyntaxError: Unexpected token a
    at Object.parse (native)
    at /Users/davidperezgar/.atom/packages/recent-projects/lib/recent-projects.js:24:25
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner-php, v1.0.0
autoclose-html, v0.18.0
autocomplete-php, v0.3.6
bootstrap3-snippets, v0.1.2
color-picker, v2.0.9
csslint, v1.1.3
file-icons, v1.5.8
highlight-line, v0.11.0
recent-projects, v0.4.3
travis-ci-status, v0.16.0
wordpress, v0.2.0

# Dev
No dev packages
```

**Comment by Ener-Getick** [comment]
Does the last version fix this error ?

**Comment by davidperezgar** [comment]
I didn't try with last version ;)

**Comment by Ener-Getick** [comment]
I changed the storage so it could be fixed ;)
