### ISSUE TITLE
Uncaught ReferenceError: dispatch is not defined

### ISSUE THREAD

**Issue by DamianKuczaj** [EXSyst/recent-projects#35]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [recent-projects](https://github.com/EXSyst/recent-projects) package, v0.8.7

### Stack Trace

Uncaught ReferenceError: dispatch is not defined

```
At C:\Users\daku\.atom\packages\recent-projects\lib\recent-projects-view.js:584

ReferenceError: dispatch is not defined
  at RecentProjectsView.module.exports.RecentProjectsView.createNewFile (C:\Users\daku\.atom\packages\recent-projects\lib\recent-projects-view.js:584:12)
  at HTMLButtonElement.<anonymous> (C:\Users\daku\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:220:36)
  at HTMLButtonElement.jQuery.event.dispatch (C:\Users\daku\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (C:\Users\daku\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -0:04.4.0 application:new-file (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "autoHideMenuBar": true,
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.1
react, v0.12.9
recent-projects, v0.8.7

# Dev
No dev packages
```

**Comment by Ener-Getick** [comment]
Oops there is a typo ... Thanks for your report.
