### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by bmcgonigle** [EXSyst/recent-projects#38]
1. Hit cmd-shift-o

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [recent-projects](https://github.com/EXSyst/recent-projects) package, v0.9.3

### Stack Trace

Uncaught TypeError: Cannot read property 'apply' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:156

TypeError: Cannot read property 'apply' of undefined
    at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:156:30)
    at Function.View.buildHtml (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:123:10)
    at RecentProjectsView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:155:33)
    at RecentProjectsView.ScrollView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new RecentProjectsView (/Users/brian/.atom/packages/recent-projects/lib/recent-projects-view.js:62:116)
    at createView (/Users/brian/.atom/packages/recent-projects/lib/main.js:15:9)
    at viewOpener (/Users/brian/.atom/packages/recent-projects/lib/main.js:58:10)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:431:22)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:374:19)
    at atom-workspace.recentProjectsOpen (/Users/brian/.atom/packages/recent-projects/lib/main.js:124:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
    at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:20)
```

### Commands

```
     -3:11.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:10.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:59.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -2:32.5.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:28.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:25.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:24.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:20.9.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -2:18.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:06.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:04.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:04.2.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -2:03.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:58.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -0:50.4.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:02.9.0 recent-projects:open (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-python-pep257"
    ],
    "projectHome": "/Users/brian/Dropbox/Programming",
    "packagesWithKeymapsDisabled": [
      "pipe"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-beautify, v0.28.16
atom-jinja2, v0.5.0
atom-yamljson, v0.2.3
autocomplete-python, v0.10.0
git-diff-details, v0.21.0
linter, v1.10.0
linter-python-pep8, v0.2.0
minimap, v4.16.0
pretty-json, v0.4.1
project-manager, v2.6.5
python-autopep8, v0.1.3
python-isort, v0.0.7
python-tools, v0.6.5
recent-projects, v0.9.3
remote-atom, v1.2.8
remote-edit, v1.8.22
script-runner, v1.8.4
tree-view-git-branch, v0.0.6
tree-view-git-projects, v0.5.0
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by Ener-Getick** [comment]
Thank you for your report.

Can you check if this error is still there in the v0.9.5 please ?

**Comment by bmcgonigle** [comment]
Works!

**Comment by Ener-Getick** [comment]
Cool :-)
