### ISSUE TITLE
Getting frequent error from dependency babel-polyfill

### ISSUE THREAD

**Issue by a-laughlin** [EXSyst/recent-projects#42]
Curious why this package would be doing anything on keystroke.  Seems like it's coming more from the keymap manager, but this package ends up throwing the error, so posting here.  Cross posting this at https://github.com/atom/atom-keymap/issues/120

[Enter steps to reproduce below:]

Unsure.  It happens sometimes when typing "let"
Result is: llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllet 

**Atom Version**: 1.6.0
**System**: Mac OS X 10.9.5
**Thrown From**: [recent-projects](https://github.com/EXSyst/recent-projects) package, v0.9.5

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

**note: trace below truncated - it repeats keymap-manager.js 551:14 and 422:21 ~1500 times**

```
At /opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/helpers.js:8

RangeError: Maximum call stack size exceeded
    at String.startsWith (native)
    at String.startsWith (/Users/adam/.atom/packages/recent-projects/node_modules/babel-polyfill/node_modules/core-js/modules/es6.string.starts-with.js:16:21)
    at matchesNextUserKeystroke (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/helpers.js:310:41)
    at exports.keystrokesMatch (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/helpers.js:328:21)
    at KeymapManager.module.exports.KeymapManager.findMatchCandidates (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:466:21)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:339:20)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:551:14)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:422:21)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:551:14)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:422:21)
   ****
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:14.4.0 core:paste (atom-text-editor.editor.is-focused)
     -2:13.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:11.3.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -2:10.8.0 core:move-right (atom-text-editor.editor.is-focused)
  5x -2:10.2.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -2:09.0 core:backspace (atom-text-editor.editor.is-focused)
  9x -1:54.3.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:49 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  8x -1:48.5.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:44.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:38.8.0 editor:move-line-up (atom-text-editor.editor.is-focused)
     -1:37.6.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -1:37 editor:delete-line (atom-text-editor.editor.is-focused)
  -- probably happens around here --
  2x -0:18 core:save (atom-text-editor.editor.is-focused)
     -0:17.9.0 window:toggle-dev-tools (atom-text-editor.editor)
     -0:17.8.0 pane:reopen-closed-item (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "spell-check",
      "editor-stats",
      "regex-railroad-diagram",
      "atom-jsfiddle",
      "autocomplete-python",
      "node-debugger"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "spell-check",
      "autocomplete-plus",
      "activate-power-mode",
      "linter",
      "atom-jsfiddle",
      "advanced-open-file",
      "tablr",
      "node-debugger",
      "recent-projects",
      "fuzzy-finder",
      "script",
      "project-manager",
      "tree-view",
      "find-and-replace",
      "split-diff",
      "aligner",
      "atom-alignment"
    ],
    "projectHome": "/Users/adam/Dropbox/repos",
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-alignment, v0.12.1
atom-autocomplete-php, v0.18.7
atom-beautify, v0.28.26
atom-ternjs, v0.13.2
autocomplete-html-entities, v0.1.0
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
coffeescript-check, v0.2.0
docblockr, v0.7.3
editorconfig, v1.2.4
expand-region, v0.2.4
file-watcher, v0.4.0
fold-functions, v0.4.3
highlight-selected, v0.11.2
language-babel, v2.16.0
language-typescript-grammars-only, v1.3.1
linter, v1.11.3
linter-eslint, v7.1.1
linter-pep8, v1.2.1
linter-tslint, v0.8.3
markdown-scroll-sync, v2.1.2
markdown-writer, v2.3.2
merge-conflicts, v1.3.7
open-recent, v5.0.0
package-manager-commands, v2.0.3
package-sync, v1.0.0
pain-split, v1.4.0
project-manager, v2.7.6
react, v0.14.1
recent-projects, v0.9.5
set-syntax, v0.3.0
split-diff, v0.6.0
tablr, v1.0.2
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

**Comment by Ener-Getick** [comment]
Thanks for the report, but I'm sorry I have no idea where does this come from...
Please ping me if you find anything else relevant which could help solving this issue.

**Comment by a-laughlin** [comment]
After more testing, I figured out how to reproduce it with no packages enabled.  Looks like a keymap issue.  Thanks for the response.  Closing!
