### ISSUE TITLE
Failed to load on 1.16 beta: "super" keyword unexpected here.

### ISSUE THREAD

**Issue by phyllisstein** [EXSyst/recent-projects#50]
Hey there! I just tried installing `recent-projects` on Atom 1.16.0-beta0, and ran into an error. It looks like it was thrown on [`recent-projects-view.js:75`](https://github.com/EXSyst/recent-projects/blob/master/lib/recent-projects-view.js#L75), which is the only place `super` appears in the code base, though I'm not altogether sure why: it looks like a perfectly cromulent use of `super` to me, and the online Babel REPL transpiles it just fine.

If you have any thoughts or suggestions about how this might be patched, I'd love to hear them! Thanks in advance for your help.

---

1. Install `recent-projects`.
2. 💥 

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [recent-projects](https://github.com/EXSyst/recent-projects) package 0.13.1

### Stack Trace

Failed to load the recent-projects package

```
At 'super' keyword unexpected here

SyntaxError: 'super' keyword unexpected here
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/recent-projects/lib/main.js:8:26)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:548:30)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:265:9)
    at ChildProcess.process.on.code (/app.asar/src/buffered-process.js:295:9)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -2:11.4.0 core:select-all (input.hidden-input)
     -2:08.9.0 core:backspace (input.hidden-input)
     -2:06.9.0 core:confirm (input.hidden-input)
     -2:00.2.0 core:select-all (input.hidden-input)
     -1:59.3.0 core:confirm (input.hidden-input)
     -1:44.4.0 find-and-replace:replace-next (input.hidden-input)
     -1:41.7.0 expose:toggle (input.hidden-input)
  2x -1:26.9.0 core:backspace (input.hidden-input)
     -1:25.6.0 core:select-all (input.hidden-input)
     -1:25.5.0 core:backspace (input.hidden-input)
     -1:23.5.0 core:select-all (input.hidden-input)
     -1:22.2.0 core:confirm (input.hidden-input)
     -0:48.5.0 core:select-all (input.hidden-input)
     -0:46.6.0 core:confirm (input.hidden-input)
     -0:30.8.0 core:select-all (input.hidden-input)
     -0:26.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
alt-up 0.4.1 
ask-stack 2.2.0 
atom-beautify 0.29.17 
atom-center-comment 0.1.1 
atom-elixir 0.2.2 
atom-fuzzy-grep 0.15.0 
atom-material-ui 1.3.9 
atom-npm-outdated 0.8.4 
autocomplete-elixir 1.5.14 
autocomplete-emojis 2.5.0 
autocomplete-json 5.3.0 
autocomplete-modules 1.6.7 
autocomplete-python 1.8.60 
blame 0.10.2 
bracket-padder 0.4.1 
browser-plus 0.0.87 
build 0.67.0 
busy 0.7.0 
character-table 0.4.3 
chmod 0.1.1 
color-picker 2.2.5 
copy-path 0.4.1 
cursor-blink-interval 0.3.1 
docblockr 0.9.1 
eslint-fixer 1.2.1 
expose 0.14.0 
file-icons 2.0.17 
file-types 0.5.5 
floobits 0.32.10 
foldingtext-for-atom 0.9.2 
foldingtext-markdown 1.3.2 
git-clone 0.2.0 
git-plus 7.3.3 
jumpy 3.1.3 
key-peek 0.2.12 
language-babel 2.56.0 
language-elixir 0.17.0 
linter 1.11.23 
linter-elixir-credo 1.1.0 
linter-eslint 8.1.3 
linter-js-yaml 1.2.7 
magic-reflow 0.3.0 
open-in-browsers 0.0.19 
project-manager 3.3.3 
quick-file-actions 0.1.1 
recent-projects 0.13.1 
set-syntax 0.3.2 
split-diff 1.2.0 
sublime-block-comment 0.5.1 
sublime-word-navigation 0.2.0 
term3 0.22.1 
```

**Comment by GuilhemN** [comment]
I don't have the time to investigate right now but I'd be happy to merge a PR ☺
